version: '2'
services:
    web:
        build: .
        environment:
            - ALLOW_OVERRIDE=true
        ports:
            - "80:80"
        dns:
            - 8.8.8.8
        links:
            - db
        # volumes:
        #     - ./code:/var/www/html
    db:
        image: mariadb
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
